FROM cmssw/el9:x86_64

WORKDIR /home/tmp

RUN curl -o actions-runner-linux-x64-2.336.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.336.0/actions-runner-linux-x64-2.336.0.tar.gz
RUN tar xzf ./actions-runner-linux-x64-2.336.0.tar.gz
RUN ./bin/installdependencies.sh

WORKDIR /home

CMD ["bash"]
