name: SCRAM Checks
description: Runs SCRAM checks
inputs:
  pr-number:
    description: PR number
    required: true
  required-prs:
    description: Comma-separated list of required PR numbers that must be merged before checks are run
    required: false
  packages:
    description: Comma-separated list of extra packages to add
    required: false
runs:
  using: composite
  steps:
    - name: Copy script to workspace
      run: cp ${{ github.action_path }}/run.sh ${{ github.workspace }}
      shell: bash
    - name: Set up environment variables
      shell: bash
      run: |
        echo "RUNNER_UID=$(id -u)" >> $GITHUB_ENV
        echo "RUNNER_GID=$(id -g)" >> $GITHUB_ENV
    - name: Mount cvmfs
      uses: cvmfs-contrib/github-action-cvmfs@v5
      with:
        cvmfs_repositories: "cms.cern.ch,cms-ib.cern.ch"
    # For some reason we need to interact with cvmfs before using it in Docker because otherwise it fails
    - name: List files in cvmfs to get it started
      run: |
        ls /cvmfs/cms.cern.ch/ > /dev/null
        ls /cvmfs/cms-ib.cern.ch/ > /dev/null
      shell: bash
    - name: Get PR target branch
      id: get_target_branch
      uses: actions/github-script@v9
      with:
        result-encoding: string
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: "cmssw",
            pull_number: "${{ inputs.pr-number }}",
          });
          return pullRequest.base.ref;
    - name: Run checks in Docker container
      shell: bash
      run: |
        docker pull cmssw/el9:x86_64
        docker run --rm \
          -v ${{ github.workspace }}:/home/TrackLooper \
          -v /cvmfs/cms.cern.ch:/cvmfs/cms.cern.ch \
          -v /cvmfs/cms-ib.cern.ch:/cvmfs/cms-ib.cern.ch \
          -w /home/TrackLooper \
          -u ${{ env.RUNNER_UID }}:${{ env.RUNNER_GID }} \
          -e PR_NUMBER=${{ inputs.pr-number }} \
          -e TARGET_BRANCH=${{ steps.get_target_branch.outputs.result }} \
          -e REQUIRED_PRS=${{ inputs.required-prs }} \
          -e PACKAGES=${{ inputs.packages }} \
          cmssw/el9:x86_64 ./run.sh
