name: Runs SCRAM static checks

on:
  workflow_call:
    inputs:
      pr-number:
        description: PR number
        required: true
        # For some reason it doesn't work if we use `number` here
        type: string
      required-prs:
        description: Comma-separated list of required PR numbers that must be merged before checks are run
        required: false
        type: string
    secrets:
      app-id:
        required: true
      app-private-key:
        required: true


jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"
