name: Runs SCRAM static checks

on:
  workflow_call:
    inputs:
      pr-number:
        description: PR number
        required: true
        type: string


jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test"
